/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as accessControlSol from "./accessControl.sol";
export type { accessControlSol };
import type * as myNftSol from "./myNFT.sol";
export type { myNftSol };
