/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as drugContractSol from "./drugContract.sol";
export type { drugContractSol };
import type * as libraries from "./libraries";
export type { libraries };
import type * as myNftSol from "./myNFT.sol";
export type { myNftSol };
