/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type AllRoleBaseStructStruct = {
  isActive: boolean;
  taxCode: string;
  licenseNo: string;
};

export type AllRoleBaseStructStructOutput = [
  isActive: boolean,
  taxCode: string,
  licenseNo: string
] & { isActive: boolean; taxCode: string; licenseNo: string };

export interface AccessControlServiceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DISTRIBUTOR_ROLE"
      | "DIST_PHAR_RELATION"
      | "MANUFACTURER_ROLE"
      | "MANU_DIST_RELATION"
      | "PHARMACY_ROLE"
      | "addDistributor"
      | "addManufacturer"
      | "addPharmacy"
      | "checkIsDistributor"
      | "checkIsManufacturer"
      | "checkIsPharmacy"
      | "getDistributor"
      | "getManufacture"
      | "getPharma"
      | "isAdmin"
      | "isDistributor"
      | "isManufacturer"
      | "isPharmacy"
      | "regrantDistributor"
      | "regrantManufacture"
      | "regrantPharmacy"
      | "removeDistributor"
      | "removeManufacturer"
      | "removePharmacy"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PermissionGranted"
      | "PermissionRevoked"
      | "regrantPermisson"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DISTRIBUTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DIST_PHAR_RELATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MANUFACTURER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MANU_DIST_RELATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PHARMACY_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addDistributor",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addManufacturer",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addPharmacy",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIsDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIsManufacturer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIsPharmacy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getManufacture",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPharma",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isManufacturer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPharmacy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "regrantDistributor",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "regrantManufacture",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "regrantPharmacy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeManufacturer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removePharmacy",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DISTRIBUTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DIST_PHAR_RELATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MANUFACTURER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MANU_DIST_RELATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PHARMACY_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addPharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkIsDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkIsManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkIsPharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getManufacture",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPharma", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPharmacy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "regrantDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "regrantManufacture",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "regrantPharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removePharmacy",
    data: BytesLike
  ): Result;
}

export namespace PermissionGrantedEvent {
  export type InputTuple = [
    granter: AddressLike,
    receiver: AddressLike,
    role: BytesLike
  ];
  export type OutputTuple = [granter: string, receiver: string, role: string];
  export interface OutputObject {
    granter: string;
    receiver: string;
    role: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PermissionRevokedEvent {
  export type InputTuple = [
    granter: AddressLike,
    receiver: AddressLike,
    role: BytesLike
  ];
  export type OutputTuple = [granter: string, receiver: string, role: string];
  export interface OutputObject {
    granter: string;
    receiver: string;
    role: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace regrantPermissonEvent {
  export type InputTuple = [
    granter: AddressLike,
    receiver: AddressLike,
    role: BytesLike
  ];
  export type OutputTuple = [granter: string, receiver: string, role: string];
  export interface OutputObject {
    granter: string;
    receiver: string;
    role: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AccessControlService extends BaseContract {
  connect(runner?: ContractRunner | null): AccessControlService;
  waitForDeployment(): Promise<this>;

  interface: AccessControlServiceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DISTRIBUTOR_ROLE: TypedContractMethod<[], [string], "view">;

  DIST_PHAR_RELATION: TypedContractMethod<[], [string], "view">;

  MANUFACTURER_ROLE: TypedContractMethod<[], [string], "view">;

  MANU_DIST_RELATION: TypedContractMethod<[], [string], "view">;

  PHARMACY_ROLE: TypedContractMethod<[], [string], "view">;

  addDistributor: TypedContractMethod<
    [_distributor: AddressLike, taxCode: string, lisenceNo: string],
    [void],
    "nonpayable"
  >;

  addManufacturer: TypedContractMethod<
    [_manufacturer: AddressLike, taxCode: string, lisenceNo: string],
    [void],
    "nonpayable"
  >;

  addPharmacy: TypedContractMethod<
    [_pharmacy: AddressLike, taxCode: string, lisenceNo: string],
    [void],
    "nonpayable"
  >;

  checkIsDistributor: TypedContractMethod<
    [_distributorAddress: AddressLike],
    [boolean],
    "view"
  >;

  checkIsManufacturer: TypedContractMethod<
    [_manufacturerAddress: AddressLike],
    [boolean],
    "view"
  >;

  checkIsPharmacy: TypedContractMethod<
    [_pharmacyAddress: AddressLike],
    [boolean],
    "view"
  >;

  getDistributor: TypedContractMethod<
    [_distributorAddress: AddressLike],
    [AllRoleBaseStructStructOutput],
    "view"
  >;

  getManufacture: TypedContractMethod<
    [_manufacturerAddress: AddressLike],
    [AllRoleBaseStructStructOutput],
    "view"
  >;

  getPharma: TypedContractMethod<
    [_pharmaAddress: AddressLike],
    [AllRoleBaseStructStructOutput],
    "view"
  >;

  isAdmin: TypedContractMethod<[_adminAddress: AddressLike], [boolean], "view">;

  isDistributor: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, string, string] & {
        isActive: boolean;
        taxCode: string;
        licenseNo: string;
      }
    ],
    "view"
  >;

  isManufacturer: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, string, string] & {
        isActive: boolean;
        taxCode: string;
        licenseNo: string;
      }
    ],
    "view"
  >;

  isPharmacy: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, string, string] & {
        isActive: boolean;
        taxCode: string;
        licenseNo: string;
      }
    ],
    "view"
  >;

  regrantDistributor: TypedContractMethod<
    [_distributor: AddressLike, taxCode: string, lisenceNo: string],
    [void],
    "nonpayable"
  >;

  regrantManufacture: TypedContractMethod<
    [_manufacturer: AddressLike],
    [void],
    "nonpayable"
  >;

  regrantPharmacy: TypedContractMethod<
    [_pharmacy: AddressLike],
    [void],
    "nonpayable"
  >;

  removeDistributor: TypedContractMethod<
    [_distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  removeManufacturer: TypedContractMethod<
    [_manufacturer: AddressLike],
    [void],
    "nonpayable"
  >;

  removePharmacy: TypedContractMethod<
    [_pharmacy: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DISTRIBUTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DIST_PHAR_RELATION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MANUFACTURER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MANU_DIST_RELATION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PHARMACY_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addDistributor"
  ): TypedContractMethod<
    [_distributor: AddressLike, taxCode: string, lisenceNo: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addManufacturer"
  ): TypedContractMethod<
    [_manufacturer: AddressLike, taxCode: string, lisenceNo: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addPharmacy"
  ): TypedContractMethod<
    [_pharmacy: AddressLike, taxCode: string, lisenceNo: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkIsDistributor"
  ): TypedContractMethod<[_distributorAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkIsManufacturer"
  ): TypedContractMethod<
    [_manufacturerAddress: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkIsPharmacy"
  ): TypedContractMethod<[_pharmacyAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getDistributor"
  ): TypedContractMethod<
    [_distributorAddress: AddressLike],
    [AllRoleBaseStructStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getManufacture"
  ): TypedContractMethod<
    [_manufacturerAddress: AddressLike],
    [AllRoleBaseStructStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPharma"
  ): TypedContractMethod<
    [_pharmaAddress: AddressLike],
    [AllRoleBaseStructStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAdmin"
  ): TypedContractMethod<[_adminAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isDistributor"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, string, string] & {
        isActive: boolean;
        taxCode: string;
        licenseNo: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isManufacturer"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, string, string] & {
        isActive: boolean;
        taxCode: string;
        licenseNo: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPharmacy"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, string, string] & {
        isActive: boolean;
        taxCode: string;
        licenseNo: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "regrantDistributor"
  ): TypedContractMethod<
    [_distributor: AddressLike, taxCode: string, lisenceNo: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "regrantManufacture"
  ): TypedContractMethod<[_manufacturer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "regrantPharmacy"
  ): TypedContractMethod<[_pharmacy: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeDistributor"
  ): TypedContractMethod<[_distributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeManufacturer"
  ): TypedContractMethod<[_manufacturer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removePharmacy"
  ): TypedContractMethod<[_pharmacy: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "PermissionGranted"
  ): TypedContractEvent<
    PermissionGrantedEvent.InputTuple,
    PermissionGrantedEvent.OutputTuple,
    PermissionGrantedEvent.OutputObject
  >;
  getEvent(
    key: "PermissionRevoked"
  ): TypedContractEvent<
    PermissionRevokedEvent.InputTuple,
    PermissionRevokedEvent.OutputTuple,
    PermissionRevokedEvent.OutputObject
  >;
  getEvent(
    key: "regrantPermisson"
  ): TypedContractEvent<
    regrantPermissonEvent.InputTuple,
    regrantPermissonEvent.OutputTuple,
    regrantPermissonEvent.OutputObject
  >;

  filters: {
    "PermissionGranted(address,address,bytes32)": TypedContractEvent<
      PermissionGrantedEvent.InputTuple,
      PermissionGrantedEvent.OutputTuple,
      PermissionGrantedEvent.OutputObject
    >;
    PermissionGranted: TypedContractEvent<
      PermissionGrantedEvent.InputTuple,
      PermissionGrantedEvent.OutputTuple,
      PermissionGrantedEvent.OutputObject
    >;

    "PermissionRevoked(address,address,bytes32)": TypedContractEvent<
      PermissionRevokedEvent.InputTuple,
      PermissionRevokedEvent.OutputTuple,
      PermissionRevokedEvent.OutputObject
    >;
    PermissionRevoked: TypedContractEvent<
      PermissionRevokedEvent.InputTuple,
      PermissionRevokedEvent.OutputTuple,
      PermissionRevokedEvent.OutputObject
    >;

    "regrantPermisson(address,address,bytes32)": TypedContractEvent<
      regrantPermissonEvent.InputTuple,
      regrantPermissonEvent.OutputTuple,
      regrantPermissonEvent.OutputObject
    >;
    regrantPermisson: TypedContractEvent<
      regrantPermissonEvent.InputTuple,
      regrantPermissonEvent.OutputTuple,
      regrantPermissonEvent.OutputObject
    >;
  };
}
