/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AccessControlServiceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DISTRIBUTOR_ROLE"
      | "DIST_PHAR_RELATION"
      | "MANUFACTURER_ROLE"
      | "MANU_DIST_RELATION"
      | "PHARMACY_ROLE"
      | "addDistributor"
      | "addManufacturer"
      | "addPharmacy"
      | "checkIsDistributor"
      | "checkIsManufacturer"
      | "checkIsPharmacy"
      | "distributorApproveManufacturer"
      | "distributorApprovePharmacy"
      | "distributorPharmacyStatus"
      | "distributorRequestManufacturer"
      | "distributorRequestPharmacy"
      | "isAdmin"
      | "isDistributor"
      | "isDistributorPharmacyApproved"
      | "isManufacturer"
      | "isManufacturerDistributorApproved"
      | "isPharmacy"
      | "manufacturerApproveDistributor"
      | "manufacturerDistributorStatus"
      | "manufacturerRequestDistributor"
      | "pharmacyApproveDistributor"
      | "pharmacyRequestDistributor"
      | "removeDistributor"
      | "removeDistributorPharmacyLink"
      | "removeManufacturer"
      | "removeManufacturerDistributorLink"
      | "removePharmacy"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PermissionGranted"
      | "PermissionRevoked"
      | "RelationshipApproved"
      | "RelationshipRejected"
      | "RelationshipRemoved"
      | "RelationshipRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DISTRIBUTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DIST_PHAR_RELATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MANUFACTURER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MANU_DIST_RELATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PHARMACY_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addManufacturer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addPharmacy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIsDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIsManufacturer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIsPharmacy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributorApproveManufacturer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributorApprovePharmacy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributorPharmacyStatus",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributorRequestManufacturer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributorRequestPharmacy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDistributorPharmacyApproved",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isManufacturer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isManufacturerDistributorApproved",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPharmacy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "manufacturerApproveDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "manufacturerDistributorStatus",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "manufacturerRequestDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pharmacyApproveDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pharmacyRequestDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeDistributorPharmacyLink",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeManufacturer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeManufacturerDistributorLink",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removePharmacy",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DISTRIBUTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DIST_PHAR_RELATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MANUFACTURER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MANU_DIST_RELATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PHARMACY_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addPharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkIsDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkIsManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkIsPharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributorApproveManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributorApprovePharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributorPharmacyStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributorRequestManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributorRequestPharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDistributorPharmacyApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isManufacturerDistributorApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPharmacy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "manufacturerApproveDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "manufacturerDistributorStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "manufacturerRequestDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pharmacyApproveDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pharmacyRequestDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeDistributorPharmacyLink",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeManufacturerDistributorLink",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removePharmacy",
    data: BytesLike
  ): Result;
}

export namespace PermissionGrantedEvent {
  export type InputTuple = [
    granter: AddressLike,
    receiver: AddressLike,
    role: BytesLike
  ];
  export type OutputTuple = [granter: string, receiver: string, role: string];
  export interface OutputObject {
    granter: string;
    receiver: string;
    role: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PermissionRevokedEvent {
  export type InputTuple = [
    granter: AddressLike,
    receiver: AddressLike,
    role: BytesLike
  ];
  export type OutputTuple = [granter: string, receiver: string, role: string];
  export interface OutputObject {
    granter: string;
    receiver: string;
    role: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelationshipApprovedEvent {
  export type InputTuple = [
    approver: AddressLike,
    requester: AddressLike,
    relationshipType: BytesLike
  ];
  export type OutputTuple = [
    approver: string,
    requester: string,
    relationshipType: string
  ];
  export interface OutputObject {
    approver: string;
    requester: string;
    relationshipType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelationshipRejectedEvent {
  export type InputTuple = [
    party1: AddressLike,
    party2: AddressLike,
    relationshipType: BytesLike
  ];
  export type OutputTuple = [
    party1: string,
    party2: string,
    relationshipType: string
  ];
  export interface OutputObject {
    party1: string;
    party2: string;
    relationshipType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelationshipRemovedEvent {
  export type InputTuple = [
    remover: AddressLike,
    otherParty: AddressLike,
    relationshipType: BytesLike
  ];
  export type OutputTuple = [
    remover: string,
    otherParty: string,
    relationshipType: string
  ];
  export interface OutputObject {
    remover: string;
    otherParty: string;
    relationshipType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelationshipRequestedEvent {
  export type InputTuple = [
    requester: AddressLike,
    approver: AddressLike,
    relationshipType: BytesLike
  ];
  export type OutputTuple = [
    requester: string,
    approver: string,
    relationshipType: string
  ];
  export interface OutputObject {
    requester: string;
    approver: string;
    relationshipType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AccessControlService extends BaseContract {
  connect(runner?: ContractRunner | null): AccessControlService;
  waitForDeployment(): Promise<this>;

  interface: AccessControlServiceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DISTRIBUTOR_ROLE: TypedContractMethod<[], [string], "view">;

  DIST_PHAR_RELATION: TypedContractMethod<[], [string], "view">;

  MANUFACTURER_ROLE: TypedContractMethod<[], [string], "view">;

  MANU_DIST_RELATION: TypedContractMethod<[], [string], "view">;

  PHARMACY_ROLE: TypedContractMethod<[], [string], "view">;

  addDistributor: TypedContractMethod<
    [_distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  addManufacturer: TypedContractMethod<
    [_manufacturer: AddressLike],
    [void],
    "nonpayable"
  >;

  addPharmacy: TypedContractMethod<
    [_pharmacy: AddressLike],
    [void],
    "nonpayable"
  >;

  checkIsDistributor: TypedContractMethod<
    [_distributorAddress: AddressLike],
    [boolean],
    "view"
  >;

  checkIsManufacturer: TypedContractMethod<
    [_manufacturerAddress: AddressLike],
    [boolean],
    "view"
  >;

  checkIsPharmacy: TypedContractMethod<
    [_pharmacyAddress: AddressLike],
    [boolean],
    "view"
  >;

  distributorApproveManufacturer: TypedContractMethod<
    [_manufacturer: AddressLike],
    [void],
    "nonpayable"
  >;

  distributorApprovePharmacy: TypedContractMethod<
    [_pharmacy: AddressLike],
    [void],
    "nonpayable"
  >;

  distributorPharmacyStatus: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  distributorRequestManufacturer: TypedContractMethod<
    [_manufacturer: AddressLike],
    [void],
    "nonpayable"
  >;

  distributorRequestPharmacy: TypedContractMethod<
    [_pharmacy: AddressLike],
    [void],
    "nonpayable"
  >;

  isAdmin: TypedContractMethod<[_adminAddress: AddressLike], [boolean], "view">;

  isDistributor: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isDistributorPharmacyApproved: TypedContractMethod<
    [_distributor: AddressLike, _pharmacy: AddressLike],
    [boolean],
    "view"
  >;

  isManufacturer: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isManufacturerDistributorApproved: TypedContractMethod<
    [_manufacturer: AddressLike, _distributor: AddressLike],
    [boolean],
    "view"
  >;

  isPharmacy: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  manufacturerApproveDistributor: TypedContractMethod<
    [_distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  manufacturerDistributorStatus: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  manufacturerRequestDistributor: TypedContractMethod<
    [_distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  pharmacyApproveDistributor: TypedContractMethod<
    [_distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  pharmacyRequestDistributor: TypedContractMethod<
    [_distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  removeDistributor: TypedContractMethod<
    [_distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  removeDistributorPharmacyLink: TypedContractMethod<
    [_otherParty: AddressLike],
    [void],
    "nonpayable"
  >;

  removeManufacturer: TypedContractMethod<
    [_manufacturer: AddressLike],
    [void],
    "nonpayable"
  >;

  removeManufacturerDistributorLink: TypedContractMethod<
    [_otherParty: AddressLike],
    [void],
    "nonpayable"
  >;

  removePharmacy: TypedContractMethod<
    [_pharmacy: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DISTRIBUTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DIST_PHAR_RELATION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MANUFACTURER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MANU_DIST_RELATION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PHARMACY_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addDistributor"
  ): TypedContractMethod<[_distributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addManufacturer"
  ): TypedContractMethod<[_manufacturer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addPharmacy"
  ): TypedContractMethod<[_pharmacy: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkIsDistributor"
  ): TypedContractMethod<[_distributorAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkIsManufacturer"
  ): TypedContractMethod<
    [_manufacturerAddress: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkIsPharmacy"
  ): TypedContractMethod<[_pharmacyAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "distributorApproveManufacturer"
  ): TypedContractMethod<[_manufacturer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributorApprovePharmacy"
  ): TypedContractMethod<[_pharmacy: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributorPharmacyStatus"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "distributorRequestManufacturer"
  ): TypedContractMethod<[_manufacturer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributorRequestPharmacy"
  ): TypedContractMethod<[_pharmacy: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isAdmin"
  ): TypedContractMethod<[_adminAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isDistributor"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isDistributorPharmacyApproved"
  ): TypedContractMethod<
    [_distributor: AddressLike, _pharmacy: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isManufacturer"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isManufacturerDistributorApproved"
  ): TypedContractMethod<
    [_manufacturer: AddressLike, _distributor: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPharmacy"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "manufacturerApproveDistributor"
  ): TypedContractMethod<[_distributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "manufacturerDistributorStatus"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "manufacturerRequestDistributor"
  ): TypedContractMethod<[_distributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pharmacyApproveDistributor"
  ): TypedContractMethod<[_distributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pharmacyRequestDistributor"
  ): TypedContractMethod<[_distributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeDistributor"
  ): TypedContractMethod<[_distributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeDistributorPharmacyLink"
  ): TypedContractMethod<[_otherParty: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeManufacturer"
  ): TypedContractMethod<[_manufacturer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeManufacturerDistributorLink"
  ): TypedContractMethod<[_otherParty: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removePharmacy"
  ): TypedContractMethod<[_pharmacy: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "PermissionGranted"
  ): TypedContractEvent<
    PermissionGrantedEvent.InputTuple,
    PermissionGrantedEvent.OutputTuple,
    PermissionGrantedEvent.OutputObject
  >;
  getEvent(
    key: "PermissionRevoked"
  ): TypedContractEvent<
    PermissionRevokedEvent.InputTuple,
    PermissionRevokedEvent.OutputTuple,
    PermissionRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RelationshipApproved"
  ): TypedContractEvent<
    RelationshipApprovedEvent.InputTuple,
    RelationshipApprovedEvent.OutputTuple,
    RelationshipApprovedEvent.OutputObject
  >;
  getEvent(
    key: "RelationshipRejected"
  ): TypedContractEvent<
    RelationshipRejectedEvent.InputTuple,
    RelationshipRejectedEvent.OutputTuple,
    RelationshipRejectedEvent.OutputObject
  >;
  getEvent(
    key: "RelationshipRemoved"
  ): TypedContractEvent<
    RelationshipRemovedEvent.InputTuple,
    RelationshipRemovedEvent.OutputTuple,
    RelationshipRemovedEvent.OutputObject
  >;
  getEvent(
    key: "RelationshipRequested"
  ): TypedContractEvent<
    RelationshipRequestedEvent.InputTuple,
    RelationshipRequestedEvent.OutputTuple,
    RelationshipRequestedEvent.OutputObject
  >;

  filters: {
    "PermissionGranted(address,address,bytes32)": TypedContractEvent<
      PermissionGrantedEvent.InputTuple,
      PermissionGrantedEvent.OutputTuple,
      PermissionGrantedEvent.OutputObject
    >;
    PermissionGranted: TypedContractEvent<
      PermissionGrantedEvent.InputTuple,
      PermissionGrantedEvent.OutputTuple,
      PermissionGrantedEvent.OutputObject
    >;

    "PermissionRevoked(address,address,bytes32)": TypedContractEvent<
      PermissionRevokedEvent.InputTuple,
      PermissionRevokedEvent.OutputTuple,
      PermissionRevokedEvent.OutputObject
    >;
    PermissionRevoked: TypedContractEvent<
      PermissionRevokedEvent.InputTuple,
      PermissionRevokedEvent.OutputTuple,
      PermissionRevokedEvent.OutputObject
    >;

    "RelationshipApproved(address,address,bytes32)": TypedContractEvent<
      RelationshipApprovedEvent.InputTuple,
      RelationshipApprovedEvent.OutputTuple,
      RelationshipApprovedEvent.OutputObject
    >;
    RelationshipApproved: TypedContractEvent<
      RelationshipApprovedEvent.InputTuple,
      RelationshipApprovedEvent.OutputTuple,
      RelationshipApprovedEvent.OutputObject
    >;

    "RelationshipRejected(address,address,bytes32)": TypedContractEvent<
      RelationshipRejectedEvent.InputTuple,
      RelationshipRejectedEvent.OutputTuple,
      RelationshipRejectedEvent.OutputObject
    >;
    RelationshipRejected: TypedContractEvent<
      RelationshipRejectedEvent.InputTuple,
      RelationshipRejectedEvent.OutputTuple,
      RelationshipRejectedEvent.OutputObject
    >;

    "RelationshipRemoved(address,address,bytes32)": TypedContractEvent<
      RelationshipRemovedEvent.InputTuple,
      RelationshipRemovedEvent.OutputTuple,
      RelationshipRemovedEvent.OutputObject
    >;
    RelationshipRemoved: TypedContractEvent<
      RelationshipRemovedEvent.InputTuple,
      RelationshipRemovedEvent.OutputTuple,
      RelationshipRemovedEvent.OutputObject
    >;

    "RelationshipRequested(address,address,bytes32)": TypedContractEvent<
      RelationshipRequestedEvent.InputTuple,
      RelationshipRequestedEvent.OutputTuple,
      RelationshipRequestedEvent.OutputObject
    >;
    RelationshipRequested: TypedContractEvent<
      RelationshipRequestedEvent.InputTuple,
      RelationshipRequestedEvent.OutputTuple,
      RelationshipRequestedEvent.OutputObject
    >;
  };
}
