/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AccessControlServiceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DistributorAuthorityPharmacyFun"
      | "DistributorUnauthorityPharmacyFun"
      | "ManufactureAuthorityDistributorFun"
      | "ManufactureUnauthorityDistributorFun"
      | "addDistributor"
      | "addManufacture"
      | "addPharmacy"
      | "checkDistributorAuthorityPharmacy"
      | "checkIsDistributor"
      | "checkIsManufactor"
      | "checkIsPharmacy"
      | "checkManufactorAuthorityDistributor"
      | "distributorAuthorityPharmacy"
      | "isAdmin"
      | "isDistributor"
      | "isManufacture"
      | "isPharmacy"
      | "manufactureAuthorityDistributor"
      | "removeDistributor"
      | "removeManufacture"
      | "removePharmacy"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PermissionRemoveEvent"
      | "distributorAuthorityEvent"
      | "distributorUnauthorityEvent"
      | "grantPermissonEvent"
      | "manufactureAuthorityEvent"
      | "manufactureUnauthorityEvent"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DistributorAuthorityPharmacyFun",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "DistributorUnauthorityPharmacyFun",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ManufactureAuthorityDistributorFun",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ManufactureUnauthorityDistributorFun",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addManufacture",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addPharmacy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkDistributorAuthorityPharmacy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIsDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIsManufactor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIsPharmacy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkManufactorAuthorityDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributorAuthorityPharmacy",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isManufacture",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPharmacy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "manufactureAuthorityDistributor",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeManufacture",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removePharmacy",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DistributorAuthorityPharmacyFun",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DistributorUnauthorityPharmacyFun",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ManufactureAuthorityDistributorFun",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ManufactureUnauthorityDistributorFun",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addManufacture",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addPharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkDistributorAuthorityPharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkIsDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkIsManufactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkIsPharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkManufactorAuthorityDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributorAuthorityPharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isManufacture",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPharmacy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "manufactureAuthorityDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeManufacture",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removePharmacy",
    data: BytesLike
  ): Result;
}

export namespace PermissionRemoveEventEvent {
  export type InputTuple = [granter: AddressLike, reciver: AddressLike];
  export type OutputTuple = [granter: string, reciver: string];
  export interface OutputObject {
    granter: string;
    reciver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace distributorAuthorityEventEvent {
  export type InputTuple = [
    DistributorAddress: AddressLike,
    PharmacyAddress: AddressLike
  ];
  export type OutputTuple = [
    DistributorAddress: string,
    PharmacyAddress: string
  ];
  export interface OutputObject {
    DistributorAddress: string;
    PharmacyAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace distributorUnauthorityEventEvent {
  export type InputTuple = [
    DistributorAddress: AddressLike,
    PharmacyAddress: AddressLike
  ];
  export type OutputTuple = [
    DistributorAddress: string,
    PharmacyAddress: string
  ];
  export interface OutputObject {
    DistributorAddress: string;
    PharmacyAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace grantPermissonEventEvent {
  export type InputTuple = [granter: AddressLike, reciver: AddressLike];
  export type OutputTuple = [granter: string, reciver: string];
  export interface OutputObject {
    granter: string;
    reciver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace manufactureAuthorityEventEvent {
  export type InputTuple = [
    ManufactorAddress: AddressLike,
    DistributorAddress: AddressLike
  ];
  export type OutputTuple = [
    ManufactorAddress: string,
    DistributorAddress: string
  ];
  export interface OutputObject {
    ManufactorAddress: string;
    DistributorAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace manufactureUnauthorityEventEvent {
  export type InputTuple = [
    ManufactorAddress: AddressLike,
    DistributorAddress: AddressLike
  ];
  export type OutputTuple = [
    ManufactorAddress: string,
    DistributorAddress: string
  ];
  export interface OutputObject {
    ManufactorAddress: string;
    DistributorAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AccessControlService extends BaseContract {
  connect(runner?: ContractRunner | null): AccessControlService;
  waitForDeployment(): Promise<this>;

  interface: AccessControlServiceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DistributorAuthorityPharmacyFun: TypedContractMethod<
    [_PharmacyAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  DistributorUnauthorityPharmacyFun: TypedContractMethod<
    [_PharmacyAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  ManufactureAuthorityDistributorFun: TypedContractMethod<
    [_DistributorAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  ManufactureUnauthorityDistributorFun: TypedContractMethod<
    [_DistributorAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  addDistributor: TypedContractMethod<
    [_Distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  addManufacture: TypedContractMethod<
    [_Manufacture: AddressLike],
    [void],
    "nonpayable"
  >;

  addPharmacy: TypedContractMethod<
    [_Pharmacy: AddressLike],
    [void],
    "nonpayable"
  >;

  checkDistributorAuthorityPharmacy: TypedContractMethod<
    [_PharmacyAddress: AddressLike],
    [boolean],
    "view"
  >;

  checkIsDistributor: TypedContractMethod<
    [_DistributorAddress: AddressLike],
    [boolean],
    "view"
  >;

  checkIsManufactor: TypedContractMethod<
    [_ManufactorAddress: AddressLike],
    [boolean],
    "view"
  >;

  checkIsPharmacy: TypedContractMethod<
    [_PharmacyAddress: AddressLike],
    [boolean],
    "view"
  >;

  checkManufactorAuthorityDistributor: TypedContractMethod<
    [_DistributorAddress: AddressLike],
    [boolean],
    "view"
  >;

  distributorAuthorityPharmacy: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isAdmin: TypedContractMethod<[_adminAddress: AddressLike], [boolean], "view">;

  isDistributor: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isManufacture: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isPharmacy: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  manufactureAuthorityDistributor: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  removeDistributor: TypedContractMethod<
    [_Distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  removeManufacture: TypedContractMethod<
    [_Manufacture: AddressLike],
    [void],
    "nonpayable"
  >;

  removePharmacy: TypedContractMethod<
    [_Pharmacy: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DistributorAuthorityPharmacyFun"
  ): TypedContractMethod<[_PharmacyAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "DistributorUnauthorityPharmacyFun"
  ): TypedContractMethod<[_PharmacyAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ManufactureAuthorityDistributorFun"
  ): TypedContractMethod<
    [_DistributorAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ManufactureUnauthorityDistributorFun"
  ): TypedContractMethod<
    [_DistributorAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addDistributor"
  ): TypedContractMethod<[_Distributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addManufacture"
  ): TypedContractMethod<[_Manufacture: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addPharmacy"
  ): TypedContractMethod<[_Pharmacy: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkDistributorAuthorityPharmacy"
  ): TypedContractMethod<[_PharmacyAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkIsDistributor"
  ): TypedContractMethod<[_DistributorAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkIsManufactor"
  ): TypedContractMethod<[_ManufactorAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkIsPharmacy"
  ): TypedContractMethod<[_PharmacyAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkManufactorAuthorityDistributor"
  ): TypedContractMethod<[_DistributorAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "distributorAuthorityPharmacy"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAdmin"
  ): TypedContractMethod<[_adminAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isDistributor"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isManufacture"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPharmacy"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "manufactureAuthorityDistributor"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeDistributor"
  ): TypedContractMethod<[_Distributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeManufacture"
  ): TypedContractMethod<[_Manufacture: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removePharmacy"
  ): TypedContractMethod<[_Pharmacy: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "PermissionRemoveEvent"
  ): TypedContractEvent<
    PermissionRemoveEventEvent.InputTuple,
    PermissionRemoveEventEvent.OutputTuple,
    PermissionRemoveEventEvent.OutputObject
  >;
  getEvent(
    key: "distributorAuthorityEvent"
  ): TypedContractEvent<
    distributorAuthorityEventEvent.InputTuple,
    distributorAuthorityEventEvent.OutputTuple,
    distributorAuthorityEventEvent.OutputObject
  >;
  getEvent(
    key: "distributorUnauthorityEvent"
  ): TypedContractEvent<
    distributorUnauthorityEventEvent.InputTuple,
    distributorUnauthorityEventEvent.OutputTuple,
    distributorUnauthorityEventEvent.OutputObject
  >;
  getEvent(
    key: "grantPermissonEvent"
  ): TypedContractEvent<
    grantPermissonEventEvent.InputTuple,
    grantPermissonEventEvent.OutputTuple,
    grantPermissonEventEvent.OutputObject
  >;
  getEvent(
    key: "manufactureAuthorityEvent"
  ): TypedContractEvent<
    manufactureAuthorityEventEvent.InputTuple,
    manufactureAuthorityEventEvent.OutputTuple,
    manufactureAuthorityEventEvent.OutputObject
  >;
  getEvent(
    key: "manufactureUnauthorityEvent"
  ): TypedContractEvent<
    manufactureUnauthorityEventEvent.InputTuple,
    manufactureUnauthorityEventEvent.OutputTuple,
    manufactureUnauthorityEventEvent.OutputObject
  >;

  filters: {
    "PermissionRemoveEvent(address,address)": TypedContractEvent<
      PermissionRemoveEventEvent.InputTuple,
      PermissionRemoveEventEvent.OutputTuple,
      PermissionRemoveEventEvent.OutputObject
    >;
    PermissionRemoveEvent: TypedContractEvent<
      PermissionRemoveEventEvent.InputTuple,
      PermissionRemoveEventEvent.OutputTuple,
      PermissionRemoveEventEvent.OutputObject
    >;

    "distributorAuthorityEvent(address,address)": TypedContractEvent<
      distributorAuthorityEventEvent.InputTuple,
      distributorAuthorityEventEvent.OutputTuple,
      distributorAuthorityEventEvent.OutputObject
    >;
    distributorAuthorityEvent: TypedContractEvent<
      distributorAuthorityEventEvent.InputTuple,
      distributorAuthorityEventEvent.OutputTuple,
      distributorAuthorityEventEvent.OutputObject
    >;

    "distributorUnauthorityEvent(address,address)": TypedContractEvent<
      distributorUnauthorityEventEvent.InputTuple,
      distributorUnauthorityEventEvent.OutputTuple,
      distributorUnauthorityEventEvent.OutputObject
    >;
    distributorUnauthorityEvent: TypedContractEvent<
      distributorUnauthorityEventEvent.InputTuple,
      distributorUnauthorityEventEvent.OutputTuple,
      distributorUnauthorityEventEvent.OutputObject
    >;

    "grantPermissonEvent(address,address)": TypedContractEvent<
      grantPermissonEventEvent.InputTuple,
      grantPermissonEventEvent.OutputTuple,
      grantPermissonEventEvent.OutputObject
    >;
    grantPermissonEvent: TypedContractEvent<
      grantPermissonEventEvent.InputTuple,
      grantPermissonEventEvent.OutputTuple,
      grantPermissonEventEvent.OutputObject
    >;

    "manufactureAuthorityEvent(address,address)": TypedContractEvent<
      manufactureAuthorityEventEvent.InputTuple,
      manufactureAuthorityEventEvent.OutputTuple,
      manufactureAuthorityEventEvent.OutputObject
    >;
    manufactureAuthorityEvent: TypedContractEvent<
      manufactureAuthorityEventEvent.InputTuple,
      manufactureAuthorityEventEvent.OutputTuple,
      manufactureAuthorityEventEvent.OutputObject
    >;

    "manufactureUnauthorityEvent(address,address)": TypedContractEvent<
      manufactureUnauthorityEventEvent.InputTuple,
      manufactureUnauthorityEventEvent.OutputTuple,
      manufactureUnauthorityEventEvent.OutputObject
    >;
    manufactureUnauthorityEvent: TypedContractEvent<
      manufactureUnauthorityEventEvent.InputTuple,
      manufactureUnauthorityEventEvent.OutputTuple,
      manufactureUnauthorityEventEvent.OutputObject
    >;
  };
}
