/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DrugContractServiceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addDistributor"
      | "addManufacture"
      | "addPharmacy"
      | "isDistributor"
      | "isManufacture"
      | "isPharmacy"
      | "removeDistributor"
      | "removeManufacture"
      | "removePharmacy"
      | "tokenIdTravelInfos"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PermissionRemoveEvent" | "grantPermissonEvent"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addManufacture",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addPharmacy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isManufacture",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPharmacy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeManufacture",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removePharmacy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenIdTravelInfos",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addManufacture",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addPharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isManufacture",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPharmacy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeManufacture",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removePharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenIdTravelInfos",
    data: BytesLike
  ): Result;
}

export namespace PermissionRemoveEventEvent {
  export type InputTuple = [granter: AddressLike, reciver: AddressLike];
  export type OutputTuple = [granter: string, reciver: string];
  export interface OutputObject {
    granter: string;
    reciver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace grantPermissonEventEvent {
  export type InputTuple = [granter: AddressLike, reciver: AddressLike];
  export type OutputTuple = [granter: string, reciver: string];
  export interface OutputObject {
    granter: string;
    reciver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DrugContractService extends BaseContract {
  connect(runner?: ContractRunner | null): DrugContractService;
  waitForDeployment(): Promise<this>;

  interface: DrugContractServiceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addDistributor: TypedContractMethod<
    [_Distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  addManufacture: TypedContractMethod<
    [_Manufacture: AddressLike],
    [void],
    "nonpayable"
  >;

  addPharmacy: TypedContractMethod<
    [_Pharmacy: AddressLike],
    [void],
    "nonpayable"
  >;

  isDistributor: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isManufacture: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isPharmacy: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  removeDistributor: TypedContractMethod<
    [_Distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  removeManufacture: TypedContractMethod<
    [_Manufacture: AddressLike],
    [void],
    "nonpayable"
  >;

  removePharmacy: TypedContractMethod<
    [_Pharmacy: AddressLike],
    [void],
    "nonpayable"
  >;

  tokenIdTravelInfos: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addDistributor"
  ): TypedContractMethod<[_Distributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addManufacture"
  ): TypedContractMethod<[_Manufacture: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addPharmacy"
  ): TypedContractMethod<[_Pharmacy: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isDistributor"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isManufacture"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPharmacy"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "removeDistributor"
  ): TypedContractMethod<[_Distributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeManufacture"
  ): TypedContractMethod<[_Manufacture: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removePharmacy"
  ): TypedContractMethod<[_Pharmacy: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenIdTravelInfos"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "PermissionRemoveEvent"
  ): TypedContractEvent<
    PermissionRemoveEventEvent.InputTuple,
    PermissionRemoveEventEvent.OutputTuple,
    PermissionRemoveEventEvent.OutputObject
  >;
  getEvent(
    key: "grantPermissonEvent"
  ): TypedContractEvent<
    grantPermissonEventEvent.InputTuple,
    grantPermissonEventEvent.OutputTuple,
    grantPermissonEventEvent.OutputObject
  >;

  filters: {
    "PermissionRemoveEvent(address,address)": TypedContractEvent<
      PermissionRemoveEventEvent.InputTuple,
      PermissionRemoveEventEvent.OutputTuple,
      PermissionRemoveEventEvent.OutputObject
    >;
    PermissionRemoveEvent: TypedContractEvent<
      PermissionRemoveEventEvent.InputTuple,
      PermissionRemoveEventEvent.OutputTuple,
      PermissionRemoveEventEvent.OutputObject
    >;

    "grantPermissonEvent(address,address)": TypedContractEvent<
      grantPermissonEventEvent.InputTuple,
      grantPermissonEventEvent.OutputTuple,
      grantPermissonEventEvent.OutputObject
    >;
    grantPermissonEvent: TypedContractEvent<
      grantPermissonEventEvent.InputTuple,
      grantPermissonEventEvent.OutputTuple,
      grantPermissonEventEvent.OutputObject
    >;
  };
}
