/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface UserTypeInterface extends Interface {
  getFunction(
    nameOrSignature: "DistributorByte" | "ManufactorByte" | "PharmacyByte"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DistributorByte",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ManufactorByte",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PharmacyByte",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DistributorByte",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ManufactorByte",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PharmacyByte",
    data: BytesLike
  ): Result;
}

export interface UserType extends BaseContract {
  connect(runner?: ContractRunner | null): UserType;
  waitForDeployment(): Promise<this>;

  interface: UserTypeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DistributorByte: TypedContractMethod<[], [string], "view">;

  ManufactorByte: TypedContractMethod<[], [string], "view">;

  PharmacyByte: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DistributorByte"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ManufactorByte"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PharmacyByte"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
